project_name: go-repo-template

release:
  prerelease: auto

changelog:
  use: github

builds:
  - binary: "{{ .ProjectName }}"
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    main: ./
    ldflags: -s -w -X main.version={{ .Tag }}

archives:
  - format: tar.gz
    wrap_in_directory: true
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}-{{ .Tag }}-checksums.txt"

signs:
  - artifacts: checksum

dockers:
  - image_templates: ["ghcr.io/sv-tools/{{ .ProjectName }}:{{ .Tag }}-amd64"]
    dockerfile: .github/Dockerfile
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url={{ .GitURL }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.version={{ .Tag }}"
      - '--label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}'
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"
  - image_templates: ["ghcr.io/sv-tools/{{ .ProjectName }}:{{ .Tag }}-arm64v8"]
    dockerfile: .github/Dockerfile
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url={{ .GitURL }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.version={{ .Tag }}"
      - '--label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}'
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"
  - image_templates: ["svtools/{{ .ProjectName }}:{{ .Tag }}-amd64"]
    dockerfile: .github/Dockerfile
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url={{ .GitURL }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.version={{ .Tag }}"
      - '--label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}'
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"
  - image_templates: ["svtools/{{ .ProjectName }}:{{ .Tag }}-arm64v8"]
    dockerfile: .github/Dockerfile
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url={{ .GitURL }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.version={{ .Tag }}"
      - '--label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}'
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"

docker_manifests:
  - name_template: "ghcr.io/sv-tools/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - "ghcr.io/sv-tools/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/sv-tools/{{ .ProjectName }}:{{ .Tag }}-arm64v8"
    create_flags:
      - --amend
  - name_template: "ghcr.io/sv-tools/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/sv-tools/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/sv-tools/{{ .ProjectName }}:{{ .Tag }}-arm64v8"
    create_flags:
      - --amend
  - name_template: "ghcr.io/sv-tools/{{ .ProjectName }}:v{{ .Major }}"
    image_templates:
      - "ghcr.io/sv-tools/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/sv-tools/{{ .ProjectName }}:{{ .Tag }}-arm64v8"
    create_flags:
      - --amend
  - name_template: "svtools/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - "svtools/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "svtools/{{ .ProjectName }}:{{ .Tag }}-arm64v8"
    create_flags:
      - --amend
  - name_template: "svtools/{{ .ProjectName }}:latest"
    image_templates:
      - "svtools/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "svtools/{{ .ProjectName }}:{{ .Tag }}-arm64v8"
    create_flags:
      - --amend
  - name_template: "svtools/{{ .ProjectName }}:v{{ .Major }}"
    image_templates:
      - "svtools/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "svtools/{{ .ProjectName }}:{{ .Tag }}-arm64v8"
    create_flags:
      - --amend

brews:
  - tap:
      owner: sv-tools
      name: homebrew-apps
    folder: Formula
    homepage: "{{ .GitURL }}"
    description: "{{ .ProjectName }}"
    license: MIT
    install: bin.install "{{ .ProjectName }}"
    test: assert_equal `#{bin}/{{ .ProjectName }} --version`, "{{ .ProjectName }} version v#{version}"
