name: Code

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main
      - "v[0-9]+.[0-9]+.[0-9]+" # old releases
  pull_request:
  schedule:
    - cron: '38 5 * * 3' # put some random time here

concurrency:
  group: ${{ format('{0}-{1}', github.workflow, github.head_ref) }}
  cancel-in-progress: true

permissions: read-all

jobs:
  UnitTestJob:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 'oldstable'
          - 'stable'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2 # immutable action, safe to use the versions
      - name: Install Go
        uses: actions/setup-go@v5.2.0 # immutable action, safe to use the versions
        with:
          go-version: ${{ matrix.go }}
      - name: Run Unit Tests
        run: go test -race -cover -coverprofile=coverage.out -covermode=atomic ./...
      - name: Codecov
        uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d # v5.4.2
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  GolangCI-Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2 # immutable action

      - name: Install Go
        uses: actions/setup-go@v5.2.0 # immutable action
        with:
          go-version: 'stable'

      - name: Run GolangCi-Lint
        uses: golangci/golangci-lint-action@2226d7cb06a077cd73e56eedd38eecad18e5d837 # v6.5.0
        with:
          version: latest

  UnitTests:
    if: ${{ always() }}
    needs: UnitTestJob
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        if: ${{ needs.UnitTestJob.result != 'success' }}
        run: exit 1
