name: "New Release"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  release-cli:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Prepare gpg
        run: |
          gpgconf --kill gpg-agent
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_PASSPHRASE }}" --output .github/sv-tools-bot.asc .github/sv-tools-bot.asc.gpg
          gpg --batch --yes --import .github/sv-tools-bot.asc
          rm .github/sv-tools-bot.asc

      - name: Allow arm Docker builds # https://github.com/linuxkit/linuxkit/tree/master/pkg/binfmt
        run: sudo docker run --privileged linuxkit/binfmt:v0.8

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: sv-tools-bot
          password: ${{ secrets.BOT_TOKEN }}

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: svtools
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --rm-dist --config .github/goreleaser-cli.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clear
        if: always()
        run: rm -f ${HOME}/.docker/config.json
